/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./pages/**/*.{js,ts,jsx,tsx,mdx}', './components/**/*.{js,ts,jsx,tsx,mdx}'],
  theme: {
    extend: {
      fontFamily: {
        sans: [
          'Inter',
          'system-ui',
          '-apple-system',
          'BlinkMacSystemFont',
          'Segoe UI',
          'Roboto',
          'sans-serif',
        ],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
      },
      fontSize: {
        '2xs': ['0.625rem', { lineHeight: '0.875rem' }],
      },
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        finance: {
          primary: '#1e3a5f',
          'primary-content': '#ffffff',
          secondary: '#2563eb',
          'secondary-content': '#ffffff',
          accent: '#0ea5e9',
          'accent-content': '#ffffff',
          neutral: '#1e293b',
          'neutral-content': '#f8fafc',
          'base-100': '#ffffff',
          'base-200': '#f1f5f9',
          'base-300': '#e2e8f0',
          'base-content': '#0f172a',
          info: '#3b82f6',
          'info-content': '#ffffff',
          success: '#16a34a',
          'success-content': '#ffffff',
          warning: '#f59e0b',
          'warning-content': '#000000',
          error: '#dc2626',
          'error-content': '#ffffff',
        },
      },
      {
        'finance-dark': {
          primary: '#3b82f6',
          'primary-content': '#ffffff',
          secondary: '#60a5fa',
          'secondary-content': '#ffffff',
          accent: '#38bdf8',
          'accent-content': '#000000',
          neutral: '#1e293b',
          'neutral-content': '#f8fafc',
          'base-100': '#0f172a',
          'base-200': '#1e293b',
          'base-300': '#334155',
          'base-content': '#e2e8f0',
          info: '#60a5fa',
          'info-content': '#000000',
          success: '#22c55e',
          'success-content': '#000000',
          warning: '#fbbf24',
          'warning-content': '#000000',
          error: '#ef4444',
          'error-content': '#ffffff',
        },
      },
    ],
    darkTheme: 'finance-dark',
    base: true,
    styled: true,
    utils: true,
  },
};
