const db = require('/sessions/admiring-keen-volta/mnt/stockmarket/packages/jobs-runtime/lib/db.js');

const MODEL = 'claude-sonnet-5';
const DATE = '2026-08-05';

const reports = [
  {
    companyId: 'NSE:ALLCARGO',
    research_axis: 'ACT_NOT_IN_TOP20', // not selected by the % / ₹Cr axis rule, but ACT tier — recorded for completeness
    tier: 'ACT',
    linkage: 'explained',
    trigger: 'Board approved a management change (new appointment/redesignation) alongside a scheduled Q1FY27 results filing; a bullish concall (quality 69.3/100) was filed the same day.',
    trigger_quantified: 'Delivery 14.9% / ₹23.5 Cr of ₹158 Cr traded, volume 55.7x average. Filing was not in the top-20 research seed (missed both delivery-% and delivery-₹Cr axis cutoffs), so its announcement PDF was not pulled this run — trigger description relies on classifier category tags + concall sentiment only.',
    concallCorroboration: { sentiment: 'Bullish', resultQualityScore: 69.3, guidanceHighlights: ['Filed same day (0d) as the move — concall sentiment corroborates but PDF not read this run'] },
    summary: 'Allcargo Logistics +?, ACT tier on unscheduled management_change + results + bullish concall (0d), but fell outside the top-20 PDF-research axis cutoffs. Directionally explained (concall + filings coincide with the move) but not verified against the primary PDF this run — flag for next-day follow-up if it stays elevated.',
  },
  {
    companyId: 'NSE:AGL',
    research_axis: 'DELIVERY_PCT',
    tier: 'ACT',
    linkage: 'explained',
    trigger: 'Wholly-owned subsidiary Ecu Global N.V. acquired a 10% stake in ECUnordicon AB (formerly ECU Worldwide Nordicon) for SEK 17.6 million.',
    trigger_quantified: 'SEK 17.6M ≈ ₹15-16 Cr at spot — a small bolt-on stake purchase relative to AGL\'s ₹1,421 Cr market cap (~1.1%). Delivery 54.7% / ₹9.35 Cr of ₹17.07 Cr traded (NSE), volume 3.7x average.',
    concallCorroboration: null,
    summary: 'Allcargo Global +9.96% on a small (~₹15-16 Cr) acquisition of a 10% stake in a Nordic freight-forwarding subsidiary. Deal size is modest relative to market cap, but delivery is unusually high (54.7%) for the size of the move, suggesting real conviction rather than a headline pop. Explained but proportionality (small deal, big delivery %) is worth flagging rather than treating as a major strategic acquisition.',
  },
  {
    companyId: 'NSE:BAJAJELEC',
    research_axis: 'DELIVERY_VALUE',
    tier: 'ACT',
    linkage: 'explained',
    trigger: 'Q1FY27 results showed a sharp margin/profit turnaround (EBIT margin 6.6% vs 2.5% YoY, PAT ₹48 Cr vs ₹1 Cr YoY) off a weak year-ago base, alongside two management changes: appointment of a new Chief Growth & New Business Officer and a revised remuneration structure for whole-time directors (Executive Chairman, MD & CEO).',
    trigger_quantified: 'Revenue ₹1,089 Cr (+2.3% YoY, muted), Gross Margin ₹352 Cr (+6.5% YoY), EBIT ₹72 Cr (+172.2% YoY, margin 6.6% vs 2.5%), PAT ₹48 Cr vs ₹1 Cr YoY (base-effect driven). Cash & equivalents ₹884 Cr. Delivery 10.0% / ₹46.9 Cr of ₹470 Cr traded, volume 70.8x average.',
    concallCorroboration: null,
    summary: 'Bajaj Electricals +? on a genuine margin turnaround quarter (EBIT margin nearly triples YoY) though revenue growth itself is muted at 2.3% — the PAT jump is largely a weak-base effect (₹1 Cr to ₹48 Cr) rather than top-line acceleration. Concurrent appointment of a Chief Growth & New Business Officer and revised WTD remuneration structure signal a management push on growth/cost discipline. Explained: filing plausibly accounts for the move, but the "10x PAT growth" headline overstates the underlying revenue trend — worth watching next quarter for confirmation that margin gains are durable, not base-effect noise.',
  },
  {
    companyId: 'NSE:STOVEKRAFT',
    research_axis: 'DELIVERY_VALUE',
    tier: 'ACT',
    linkage: 'explained',
    trigger: 'Q1FY27 results filed (revenue ₹480.6 Cr, +16% QoQ from ₹414.5 Cr; YoY figure not reliably extractable from the OCR\'d PDF) alongside board approval of two reappointments — an Independent Director (2nd 5-year term) and the Executive Director (further 5-year term) — which is routine board renewal, not a fresh management change. A same-day Bullish concall (quality 67.1/100, 2 days before the move) flagged a 14-15% EBITDA margin target, a China JV, and IKEA supply contract commencement.',
    trigger_quantified: 'Revenue ₹480.6 Cr vs ₹414.5 Cr prior quarter (+16.0% QoQ). PAT/EBITDA figures in the results PDF were not reliably legible (OCR corruption in the tabular section) and are not quoted here to avoid citing unverified numbers. Delivery 12.8% / ₹35.1 Cr of ₹274 Cr traded, volume 17.9x average.',
    concallCorroboration: { sentiment: 'Bullish', resultQualityScore: 67.1, guidanceHighlights: ['14-15% EBITDA margin target', 'China triply manufacturing JV', 'IKEA supply contract commencement'] },
    summary: 'Stove Kraft +? on QoQ revenue growth (+16%) and a Bullish concall (2 days prior) guiding to a 14-15% EBITDA margin target plus a new IKEA supply contract and China JV. The "management_change" tag in this run is a routine director reappointment, not a new hire/resignation — don\'t overweight it as a catalyst. PAT/EBITDA from the results PDF itself were not reliably legible via OCR; the concall guidance is the stronger, cleaner evidence here. Explained, with the caveat that headline financial figures should be re-verified from a clean source before being repeated.',
  },
  {
    companyId: 'NSE:SOTL',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'explained',
    trigger: 'Record Q1FY27 quarterly performance: highest-ever quarterly revenue and PBT.',
    trigger_quantified: 'Total Income ₹1,512.7 Cr (+49.2% YoY vs ₹1,013.6 Cr), EBITDA ₹396.7 Cr (+370.6% YoY), EBITDA margin 26.2% (vs 8.3% YoY), PBT ₹386.6 Cr (+434.7% YoY vs ₹72.3 Cr). Delivery 23.3% / ₹111.25 Cr of ₹478 Cr traded, volume 9.7x average.',
    concallCorroboration: null,
    summary: 'Savita Oil Technologies delivered a genuine record quarter — revenue +49.2% YoY and PBT +434.7% YoY with EBITDA margin more than tripling to 26.2%. This is a clean, well-quantified beat (company\'s own earnings release, not just a filing) and the delivery value (₹111 Cr) is among the largest in this scan. Explained, high-quality trigger.',
  },
  {
    companyId: 'NSE:GMMPFAUDLR',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'explained',
    trigger: 'Q1FY27 results: revenue +16% YoY, PAT +118% YoY, order backlog at a fresh high.',
    trigger_quantified: 'Revenue +16% YoY / -2% QoQ. EBITDA -7% YoY / +25% QoQ. PAT +118% YoY / +44% QoQ. Order backlog ₹2,289 Cr, +20% YoY / +4% QoQ. Delivery 13.8% / ₹83.3 Cr of ₹605 Cr traded, volume 66.3x average.',
    concallCorroboration: null,
    summary: 'GMM Pfaudler +? on a genuine PAT beat (+118% YoY) and a growing order backlog (₹2,289 Cr, +20% YoY), though EBITDA was actually down YoY (mix/margin pressure) before recovering QoQ. Explained: the PAT and backlog growth plausibly account for the move, but the YoY EBITDA decline is a mild mismatch worth flagging rather than a clean beat across every line.',
  },
  {
    companyId: 'NSE:NAVINFLUOR',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'explained',
    trigger: 'Board approved ₹90 Cr capex for adoption capacities in the Advanced Materials portfolio at the Surat unit, filed alongside Q1FY27 results on the same day.',
    trigger_quantified: '₹90 Cr capex approval (Surat unit, Advanced Materials, lab-to-commercial-scale qualification). Detailed P&L figures in the results annexure were not reliably legible via OCR and are not quoted. Delivery 14.8% / ₹475.2 Cr of ₹3,205 Cr traded (largest ₹Cr delivery in this scan), at/near window high, volume 30.7x average.',
    concallCorroboration: null,
    summary: 'Navin Fluorine had the single largest rupee delivery value in this scan (₹475 Cr) on a same-day combination of Q1FY27 results and a concrete forward-looking capex approval (₹90 Cr for Advanced Materials capacity). The capex number is clean and citable; the results P&L itself was not reliably legible from OCR. Explained — large, real money behind the move, with a specific forward catalyst (new capacity) rather than just a results non-event.',
  },
  {
    companyId: 'NSE:NEULANDLAB',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'explained',
    trigger: 'Q1FY27 results sharply beat prior-year base: Total Income +116.3% YoY, EBITDA +448.2% YoY at 35.5% margin (+2,150 bps), PAT +975.0% YoY.',
    trigger_quantified: 'Total Income ₹650.1 Cr (+116.3% YoY), EBITDA ₹231.1 Cr (+448.2% YoY), EBITDA margin 35.5% (+2150 bps YoY), PAT ₹147.4 Cr (+975.0% YoY), net cash ₹308.5 Cr (vs ₹164.7 Cr a year ago). Working capital days improved from 137 to 84. Capex outflow ₹122 Cr in the quarter. Delivery 19.4% / ₹390 Cr of ₹2,013 Cr traded, volume 27.0x average. Same-day Optimistic concall, quality 96.2/100 (highest resultQualityScore in this run) — highlights include peptide facility commissioning next month and working-capital improvement; one note flagged FY27 development-revenue quantification was withheld.',
    concallCorroboration: { sentiment: 'Optimistic', resultQualityScore: 96.2, guidanceHighlights: ['Peptide facility commissioning next month', 'FY27 development revenue quantification declined (withheld by mgmt)', 'Working capital 137 → 84 days'] },
    summary: 'Neuland Laboratories posted one of the cleanest, best-quantified beats in this scan: PAT nearly 11x YoY, EBITDA margin up over 2,100 bps, on genuine revenue growth (+116% YoY, not just a low base — Q1FY26 was already a real quarter). ₹390 Cr of delivery-backed buying (2nd largest ₹Cr in scan) and a same-day 96.2-quality Optimistic concall corroborate. The one caveat management itself flagged: FY27 development-revenue quantification was withheld this quarter, which is worth tracking. Explained, high-conviction beat.',
  },
  {
    companyId: 'NSE:MAZDOCK',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'Scheduled Q1FY27 results were filed the same period as the move, but the tabular P&L in the PDF was too OCR-corrupted to extract reliable revenue/PAT figures — headline direction (up or down) could not be confirmed from the primary source this run.',
    trigger_quantified: 'Delivery 24.9% / ₹260.7 Cr of ₹1,046 Cr traded (3rd largest ₹Cr delivery in this scan), volume 6.5x average. No verified P&L numbers to cite.',
    concallCorroboration: null,
    summary: 'Mazagon Dock had ₹261 Cr of delivery-backed buying — real institutional-scale money — coinciding with a scheduled results filing, but the results PDF text extraction was too garbled to confirm whether the quarter was a beat or miss. Labelled unexplained rather than assumed positive: the delivery is real, but the causal link to a specific number is not verified this run. Re-check with a cleaner PDF source or the concall transcript if this name stays elevated.',
  },
  {
    companyId: 'NSE:BOSCH-HCIL',
    research_axis: 'DELIVERY_PCT',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'Q1FY27 results filed same day as the move, but P&L figures were not reliably legible from the OCR\'d PDF.',
    trigger_quantified: 'Delivery 47.8% / ₹17.5 Cr of ₹36.6 Cr traded (high % delivery on a small-value base), at/near window high, volume 5.9x average, RSI 82.4 (extended/overbought).',
    concallCorroboration: null,
    summary: 'Bosch Home Comfort +? on very high delivery (47.8%, at/near a window high) alongside a results filing whose figures could not be reliably confirmed from OCR. RSI at 82.4 flags the move as technically extended. Unexplained pending a clean read of the actual results — high conviction on delivery, but the "why" is not independently verified this run.',
  },
  {
    companyId: 'NSE:IGARASHI',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'Q1FY27 results filed (two filings — results + a further disclosure), but P&L figures were not reliably legible from the OCR\'d PDFs.',
    trigger_quantified: 'Delivery 7.1% / ₹28.7 Cr of ₹404 Cr traded, volume 151.2x average — the largest volume spike in this scan by a wide margin, on modest % delivery.',
    concallCorroboration: null,
    summary: 'Igarashi Motors saw an extreme 151x volume spike alongside a results filing, but only 7.1% of traded value converted to delivery and the results PDF text could not be reliably parsed. The volume/delivery mismatch (huge turnover, low delivery %) suggests this may be more trading/arbitrage activity than durable accumulation. Unexplained — flagging the volume-delivery mismatch rather than assuming a fundamental cause.',
  },
  {
    companyId: 'NSE:INDOMIM',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'No STRONG announcement in the scan window — the move has no discoverable filing-based trigger.',
    trigger_quantified: 'Delivery 21.6% / ₹178.6 Cr of ₹827 Cr traded, at/near window high. No STRONG filing exists to explain the move.',
    concallCorroboration: null,
    summary: 'Indo-MIM +? with real delivery-backed buying (₹179 Cr) and no corresponding STRONG announcement. This is early accumulation ahead of news or a broader thematic/index-flow move — genuinely interesting but explicitly unexplained. Nothing to confirm or deny a specific cause this run.',
  },
  {
    companyId: 'NSE:TATATECH',
    research_axis: 'DELIVERY_VALUE',
    tier: 'WATCH',
    linkage: 'mismatched',
    trigger: 'Only a SUPPORTING (non-STRONG) announcement in the scan window; novelty flagged as "restates prior disclosures." An Optimistic concall (quality 49/100, filed 20 days prior — outside the 7-day credit window) had flagged non-anchor auto revenue +56.3% YoY and FY27 growth-acceleration guidance, and a Tenneco transformation program ramp-up.',
    trigger_quantified: 'Delivery 22.7% / ₹154 Cr of ₹677 Cr traded, at/near window high, volume 9.1x average. Concall was 20 days old — too stale to credit as same-week corroboration under this run\'s rules, though the guidance direction (accelerating FY27 growth) is directionally consistent with the move.',
    concallCorroboration: { sentiment: 'Optimistic', resultQualityScore: 49, guidanceHighlights: ['Non-anchor auto revenue +56.3% YoY', 'FY27 growth acceleration guidance', 'Tenneco transformation program ramp-up (flagged as still ramping, not yet delivering)'] },
    summary: 'Tata Technologies +? with only a routine/repeat announcement in-window (no STRONG filing) — flagged as mismatched rather than explained, since the only filing on record restates prior disclosures. The best available context is a 20-day-old Optimistic concall on FY27 growth acceleration, which is too old to be treated as this week\'s trigger. Worth a closer look at whether this is index/thematic flow rather than company-specific news.',
  },
  {
    companyId: 'NSE:HLEGLAS',
    research_axis: 'DELIVERY_PCT',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'No STRONG announcement in the scan window.',
    trigger_quantified: 'Delivery 51.6% / ₹24.5 Cr of ₹47.4 Cr traded (highest % delivery among WATCH names), at/near window high, volume 4.1x average.',
    concallCorroboration: null,
    summary: 'HLE Glascoat +? with the highest delivery percentage (51.6%) of any WATCH-tier name and no discoverable filing trigger. Small absolute value (₹24.5 Cr) but a strong conviction signal on a percentage basis. Unexplained — flag as early accumulation candidate to watch for a follow-through filing.',
  },
  {
    companyId: 'NSE:PANAMAPET',
    research_axis: 'DELIVERY_PCT',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'No STRONG announcement in the scan window.',
    trigger_quantified: 'Delivery 41.1% / ₹22.5 Cr of ₹54.7 Cr traded, volume 4.0x average.',
    concallCorroboration: null,
    summary: 'Panama Petrochem +? with decent delivery-backed buying and no filing trigger. Lower conviction score (2.5) than most WATCH names — genuinely unexplained, nothing more to add this run.',
  },
  {
    companyId: 'NSE:KWIL',
    research_axis: 'DELIVERY_PCT',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'No STRONG announcement in the scan window.',
    trigger_quantified: 'Delivery 40.7% / ₹38.7 Cr of ₹95 Cr traded, volume 3.5x average.',
    concallCorroboration: null,
    summary: 'Kwality Walls India +? with decent delivery and no filing trigger. Unexplained, low conviction score (2.5) — nothing more to add this run.',
  },
  {
    companyId: 'NSE:FCL',
    research_axis: 'DELIVERY_PCT',
    tier: 'WATCH',
    linkage: 'unexplained',
    trigger: 'No STRONG announcement in the scan window. An Optimistic concall (quality 66.6/100, filed 13 days prior — outside the 7-day credit window) had flagged a $100M FY27 oil & gas target and a Saudi Aramco specialty-package win.',
    trigger_quantified: 'Delivery 42.0% / ₹43.6 Cr of ₹104 Cr traded, volume 2.0x average. Concall too old (13d) to credit as this week\'s corroboration.',
    concallCorroboration: { sentiment: 'Optimistic', resultQualityScore: 66.6, guidanceHighlights: ['$100M FY27 oil & gas target', 'Saudi Aramco specialty package win', 'CrudeChem standalone margins undisclosed'] },
    summary: 'Fineotex Chemical +? with decent delivery and no in-window filing. A 13-day-old Optimistic concall (Saudi Aramco win, $100M FY27 oil & gas target) is directionally supportive but stale relative to this move. Unexplained for this run\'s window; the concall content is worth revisiting if the stock holds these gains.',
  },
];

let saved = 0;
for (const r of reports) {
  const { companyId, research_axis, tier, linkage, trigger, trigger_quantified, concallCorroboration, summary } = r;
  const id = db.saveReport({
    creator: 'gainers-signal',
    type: 'gainers-trigger-research',
    date: DATE,
    companyId,
    modelUsed: MODEL,
    summary,
    research_axis,
    tier,
    trigger,
    trigger_quantified,
    linkage,
    contextUsed: [],
    concallCorroboration,
  });
  console.log('saved', companyId, '->', id);
  saved++;
}
console.log('TOTAL SAVED:', saved);
