#!/usr/bin/env node
'use strict';

/**
 * Vendor the canonical client port into each cloud skill that needs it.
 *
 * Cloud skills run from the cloud and can't import this package, so each carries
 * its own copy of the relevant client code under scripts/_vendor/. This script is
 * the ONLY thing that writes those copies — treat scripts/_vendor/ as generated.
 *
 * Usage:
 *   node sync-skills.js --skills-root /path/to/your/skill-sources
 *   node sync-skills.js --check       # exit 1 if any vendored copy is stale (CI gate)
 *
 * --skills-root may also be set via the SKILLS_ROOT env var.
 */

const fs = require('fs');
const path = require('path');

const ROOT = __dirname;
const PY_DIR = path.join(ROOT, 'python');
const manifest = JSON.parse(fs.readFileSync(path.join(ROOT, 'skills.manifest.json'), 'utf8'));

function arg(name) {
  const i = process.argv.indexOf(name);
  return i >= 0 ? process.argv[i + 1] : null;
}
const CHECK = process.argv.includes('--check');
const skillsRoot = arg('--skills-root') || process.env.SKILLS_ROOT;

if (!skillsRoot) {
  console.error(
    'ERROR: pass --skills-root <dir> (or set SKILLS_ROOT) — the folder holding your skill sources.'
  );
  process.exit(2);
}

let stale = 0;
let written = 0;

for (const [skill, files] of Object.entries(manifest.skills)) {
  const vendorDir = path.join(skillsRoot, skill, manifest.vendorDir);
  for (const file of files) {
    const src = path.join(PY_DIR, file);
    if (!fs.existsSync(src)) {
      console.error(`  MISSING SOURCE: ${src}`);
      process.exit(2);
    }
    const dest = path.join(vendorDir, file);
    const srcContent = fs.readFileSync(src, 'utf8');
    const destExists = fs.existsSync(dest);
    const destContent = destExists ? fs.readFileSync(dest, 'utf8') : null;

    if (srcContent === destContent) continue;

    if (CHECK) {
      console.error(`  STALE: ${path.relative(skillsRoot, dest)}`);
      stale += 1;
      continue;
    }
    fs.mkdirSync(vendorDir, { recursive: true });
    // Mark the file as generated so nobody hand-edits it.
    const banner =
      '# AUTO-GENERATED by @stock/api sync-skills.js — DO NOT EDIT.\n' +
      '# Edit packages/stock-api/python/' + file + ' and re-run the sync.\n';
    fs.writeFileSync(dest, banner + srcContent);
    console.log(`  vendored ${file} -> ${skill}/${manifest.vendorDir}/`);
    written += 1;
  }
}

if (CHECK) {
  if (stale > 0) {
    console.error(`\n${stale} vendored file(s) stale. Run: node sync-skills.js --skills-root <dir>`);
    process.exit(1);
  }
  console.log('All vendored skill copies are up to date.');
} else {
  console.log(`\nDone. ${written} file(s) vendored across ${Object.keys(manifest.skills).length} skills.`);
}
